apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-app
        image: nextgenadarsh/nginx
        ports:
        - containerPort: 80

# kubectl get rs web-app
# kubectl autoscale rs web-app --max=5 --min=3 --cpu-percent=50