apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-app
        image: nextgenadarsh/nginx
        ports:
        - containerPort: 80
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1

# kubectl set image deployment web-app nextgenadarsh/nginx
# kubectl set image deployment web-app web-app=nextgenadarsh/nginx:latest
# k describe deploy web-app
# kubectl rollout status deployment/web-app
# kubectl rollout history deployment/web-app
# kubectl rollout undo deployment/web-app
# kubectl rollout undo deployment/web-app --to-revision=2
# kubectl scale deployment web-app --replicas=5
# kubectl autoscale deployment/web-app --min=10 --max=15 --cpu-percent=80
# kubectl rollout pause deployment/web-app
# kubectl rollout resume deployment/web-app
# 
