apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: frontend
    env: prod
spec:
  containers:
  - name: web-app
    image: nextgenadarsh/nginx
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3
      httpGet:
        path: /healthz
        port: liveness-port
    startupProbe:
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10

